<div id="admin_control">
    <span id="extra_span"></span>
    <div id="controlBar">
        <ul>
            <li class="controlItem"><a href="#">User</a></li>
            <li class="controlItem"><a href="#">Interface</a></li>
            <li class="controlItem"><a href="../admin/admin_content.php">Content</a></li>
            <li class="controlItem"><a href="#">Thread Management</a></li>
            <li class="controlItem"><a href="#">Post Management</a></li>
            <li class="controlItem"><a href="../index.php">Quit</a></li>
        </ul>
    </div>
</div>